### ISSUE TITLE
Remove unused library

### ISSUE THREAD

**Issue by jekiapp** [ibm-bluemix-mobile-services/bms-clientsdk-android-core#13]
I used to develop GCM on my apps with library `com.google.android.gms:play-services-gcm:(version)`. It only takes few times to compile. Now I try bluemix sdk and it takes more than 5 minutes to build. I realized this library compile the whole play services library, that's why it takes more time. 
why you even need to compile all of it if you just need `play-services-gcm`? do you even need service like maps, ads, auth, etc from google?

**Comment by dgonz7** [comment]
Both the core SDK itself and the apps that use it take less than a minute to build for me, so not sure why you are seeing that.

What other dependencies do you have in your application? Are you using multiDex? Which specific service(s) are you trying to use (push, analytics, etc.)? Because the Core SDK (which is this repository that you posted on) does not include Play services.

Please add more details in order to find the cause of the problem.

**Comment by jekiapp** [comment]
I am using ibm mobile-push service, but the github page seems can't receiving issue submit, so I submitted here. 

my gradle dependencies just `com.android.support:appcompat-v7:23.3.0` and `com.ibm.mobilefirstplatform.clientsdk.android:push:2.0.1`

multiDex is another issue, if I add few more library my application got an error because exceeded 65,536 limit. that's why google give options with [selective compiling](https://developers.google.com/android/guides/setup#add_google_play_services_to_your_project)  play service library.

by my experience, my machine build about 5 minutes if I compile the whole play service API `com.google.android.gms:play-services:9.0.2` because it bundle all the google api, but just 90 seconds if I selectively pick API let's say `com.google.android.gms:play-services-maps:9.0.2` or `com.google.android.gms:play-services-gcm:9.0.2`

**Comment by dgonz7** [comment]
Oh ok, I get it. We'll look into it, and I'll move the issue to the push repo to make it easier to track.

**Comment by dgonz7** [comment]
Version 2.0.3 of the Push SDK is now published with the fixes.
